### ISSUE TITLE
Efel Segmentation faults

### ISSUE THREAD

**Issue by dpchapma** [BlueBrain/eFEL#215]
I'm trying to do a Deap optimization with efel on a ball and stick model. I'm using efel to extract features of a current clamp experiment from both my experimental data as well as simulated data but am getting intermittent segmentation faults (seg fault 11 specifically). I tried the optimization on both my local device as well as a google HPC and am getting seg faults on both. Using a fault handler I was able to traceback the specific lines of code that are throwing the fault and the source is always from the efel api line 494 (whether or not I'm extracting data from experimental data or simulated data). I noticed that some features have a higher propensity for throwing these faults than others ex: AP upstroke always throws the fault whereas spikecount never does, but seeing as though I'm extracting ~16 features I need all of them to work. Is anyone else having issues with this? If so how did you fix them? Screenshots of code can be provided if need be. I'm also parallelizing the code with scoop, but even when I run it without parallelization I'm still getting the faults.

**Comment by wvangeit** [comment]
Would it be possible to provide us with a reproducable example? Maybe if you could dump the trace(s) that causes the issue, and the name of the features.
Thank you.

**Comment by dpchapma** [comment]
Thanks for the quick response:

I have a function "get_data" 
[GetData.py.zip](https://github.com/BlueBrain/eFEL/files/6540110/GetData.py.zip)
that takes input of a path to a folder containing abf files for a current clamp experiment 
[StephCCDat.zip](https://github.com/BlueBrain/eFEL/files/6540134/StephCCDat.zip)
and extracts 22 features from them to return the mean and STD's across cells at each current step. The most important feature that throws the error for me is "AP_width" as this makes the spiking behavior of my models wonky (but I've noticed a couple others too like AP_upstroke). I've included this in the function above (which throws the error), but when I comment out that one feature the code runs fine. The example I've provided is for experimental data but the same thing happens with my simulated data from models I've generated. 

When I run it from the terminal using fault handler, this is the traceback I get:
![Screen Shot 2021-05-25 at 10 47 03 AM](https://user-images.githubusercontent.com/57784139/119518485-8ca64780-bd46-11eb-9ecc-0d03465e869e.png)

Just some other information: I'm running python 3.7 through anaconda3. Neuron 7.8, and the latest efel update: 3.1.96.

Any help is appreciated!
Thanks

**Comment by wvangeit** [comment]
@anilbey or @AurelienJaquier , do you mind having a look? Thx.

**Comment by AurelienJaquier** [comment]
Hi!
Your issue should be solved with the latest version of efel. 
Do not hesitate to tell us if you have any other problems.

**Comment by dpchapma** [comment]
Thank you, looks like AP upstroke is working now but I'm still getting the error for AP_width, would it be possible to fix that too?

**Comment by AurelienJaquier** [comment]
I do not get any segmentation fault for AP_width with the example you provided. Do you have one when running this example? If the error occurs with another script, could you share it?

**Comment by dpchapma** [comment]
I have a fault when running the example given above. I use the same feature and a similar script when running the simulations from my neuron model but I don't get the error then. This makes me think it could be a problem with the data itself. I tried the same script with data from our other experimental group and actually was able to run the script no problem. I think that is the issue, I will just identify the bad file and remove it, thank you!
